config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, :path_prefix => "my", skip: :registration
  resources :users, only: [:edit, :update, :destroy]
  resources :executives, except: :show
  resources :archives, only: [:destroy]
  resources :accounts, shallow: true do
    resources :projects, except: [:index] do
      resources :comments , only: [:create, :destroy]
    end
  end
  get '/projectstatus/:id/:status', to: 'projects#update_status', as: 'update_project_status'
  get '/archivestatus/:id/:status', to: 'projects#update_approval_archive', as: 'update_archive_status'
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :tag, optional: true
  belongs_to :account
  has_many :archives, inverse_of: :project, dependent: :destroy
  has_many :comments, dependent: :destroy

  enum status: { in_progress: 0, delivered: 1, approved: 2, rejected: 3 }
  enum kind: { default: 0, multichoice: 1, grilla: 2 }

  accepts_nested_attributes_for :tag, reject_if: :all_blank
  accepts_nested_attributes_for :archives, reject_if: :all_blank, allow_destroy: true

  def all_archives_approved?
    !archives.map {|archive| archive.approved }.include?(false)
  end

  def all_my_attachments
    archives.map {|archive| archive}
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :is_admin?
  before_action :set_account, only: [:new, :create]
  before_action :set_project, except: [:create, :new, :update_status, :update_approval_archive]
  # before_action :set_blobs, only: [:show, :edit]
  before_action :is_client?, only: [:show]
  before_action :is_delivered?, only: [:show]
  before_action :is_default?, only: [:show]
  before_action :redirect_if_not_admin_or_associated_executive, except: [:show, :update_status, :update_approval_archive ]
  before_action :redirect_if_not_admin_or_related, only: :show

  def show
    @comentarios = @project.comments
    @comments = @project.comments.build
  end

  def new
    @project = @account.projects.build
    @tag = @project.build_tag
    @archives = @project.archives.build
    @tags = @account.all_my_tags_uniq_name
  end

  def create
    @project = @account.projects.build(project_params)

    if @project.tag then @project.tag.name.upcase! end

    if @project.save
      if @project.tag then @project.tag.name.upcase! end
      @project.save
      redirect_to project_path(@project), notice: 'Project was successfully created.'
    else
      @tags = @project.account.all_my_tags
      render :new
    end
  end

  def edit
    @account = @project.account
    @tag = Tag.new
    @archivos = @project.all_my_attachments
    @archives = @project.archives.build
    @tags = @account.all_my_tags_uniq_name
  end

  def update
    if @project.update(project_params)
      if @project.tag then @project.tag.name.upcase! end
      if  @project.status == "delivered" then UserMailer.project_delivered(@project.account.client,@project).deliver_now end
      if  (@project.status == "approved" || @project.status == "rejected") 
        UserMailer.project_evaluated(@project.account.executive,@project).deliver_now 
      end
      @project.save
      redirect_to project_path(@project), notice: 'Your info was successfully updated.'
    else
      @account = @project.account
      @tag = Tag.new
      @archivos = @project.all_my_attachments
      @archives = @project.archives.build
      @tags = @project.account.all_my_tags
      render :edit
    end
  end

  def destroy
    @account = @project.account
    @tag = @project.tag
    if @project.destroy
      if @tag.projects.empty? then @tag.destroy end
      redirect_to account_path(@account), notice: "Info was successfully destroyed"
    end
  end

  def update_status
    @project = Project.find(params[:id])
    case params[:status]
    when "aprobado"
      @project.update({status: "approved"})
      redirect_to project_path(@project), notice: "Info was successfully destroyed"
    when "rechazado"
      @project.update({status: "rejected"})
      redirect_to project_path(@project), notice: "Info was successfully destroyed"
    when "delivered"
      @project.update({status: "delivered"})
      redirect_to edit_project_path(@project), notice: "Info was successfully destroyed"
    when "in_progress"
      @project.update({status: "in_progress"})
      redirect_to edit_project_path(@project), notice: "Info was successfully destroyed"
    end
  end

  def update_approval_archive
    @project = Project.find(params[:project_id])
    @archive = Archive.find(params[:id])
    case params[:status]
    when "aprobado"
      @archive.update({approved: true})
      @project.update({status: "approved"})
      redirect_to project_path(@project), notice: "Info was successfully destroyed"
    when "rechazado"
      @archive.update({approved: false})
      redirect_to project_path(@project), notice: "Info was successfully destroyed"
    end
  end

  private

  def set_account
    @account = Account.find(params[:account_id])
  end

  def set_project
    @project = Project.find(params[:id])
  end

  def set_blobs
    @archives = Project.find(params[:id]).archives
    @images = @archives.documents
    # Archive.all[3].document.attachment.blob
  end

  def project_params
    params.require(:project).permit(:name, :description, :account_id,
      :responsible, :kind, :status, :start_date, :deadline, :next_steps,
      :tag_id, tag_attributes: [:name], archives_attributes: [:id, :title, :description, :document])
  end

  def is_admin?
    @is_admin = current_user.profile.role_id == 1
  end

  def is_client?
    @is_client = @project.account.client_id == current_user.id
  end

  def is_delivered?
    @is_delivered = @project.status == "delivered"
  end

  def is_default?
    @is_default = @project.kind == "default"
  end

  def redirect_if_not_admin_or_associated_executive
    if @project
      @is_executive_in_charge = @project.account.executive_id == current_user.id
    else
      @is_executive_in_charge = @account.executive_id == current_user.id
    end
    unless @is_executive_in_charge || @is_admin then redirect_to root_path end
  end

  def redirect_if_not_admin_or_related
    @is_executive_in_charge = @project.account.executive_id == current_user.id
    @is_client = @project.account.client_id == current_user.id
    unless @is_executive_in_charge || @is_admin || @is_client then redirect_to root_path end
  end

  def controller_action
    status = params[:status]
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_archive_fields.html.haml
.nested-fields
    .form-group
        %label.custom-file
            =f.file_field :document, class: 'dropify custom-filhhe-input', type: "file", id: "file"
            -# %span.custom-file-control.btn.btn-info Choose file

    .form-inline
        .form-group
            =f.label :title, 'Titulo (opcional):', class: 'mr-4'
            =f.text_field :title, class: 'form-control'

    =link_to_remove_association "Remover Archivo", f
    %hr

app/views/projects/edit.html.haml
%section.dashbrds
  = render :partial => 'shared/sidebar'
  %div.center
    %div.container
      %header.centered.flexc-r
        %div.link
          %div.back
            = link_to '<', :back, class: "icon"
            = link_to 'Volver', :back
          %h3.dashboard-title= "Editar Proyecto"

        -if @project.status == "in_progress"
          %p.small-pad.iconsfont.status.in_progress En Progreso
        -elsif @project.status == "delivered"
          %p.small-pad.iconsfont.status &#xF0A9
        -elsif @project.status == "rejected"
          %p.small-pad.iconsfont.status.rejected &#xF165
        -elsif @project.status == "approved"
          %p.small-pad.iconsfont.status.approved &#xF164
      %hr.centered/
      %br/


      = form_with(model: @project, local: true) do |form|
        %section.centered.form
          - if @project.errors.any?
            #error_explanation
              %h2
                = pluralize(@project.errors.count, "error")
                prohibited this profile from being saved:
              %ul
                - @project.errors.full_messages.each do |message|
                  %li= message

          %div.flexc-r.space-between
            %h3.flex100 Datos del Proyecto
            - if @project.status == "in_progress"
              =link_to 'Entregar', update_project_status_path(id: @project.id, status: "delivered"), class: 'btn btn-dark selectit'
            - else @project.status == "delivered"
              =link_to 'En Progreso de Nuevo', update_project_status_path(id: @project.id, status: "in_progress"), class: 'btn btn-dark selectit'

          .form-group
            = form.label :name, 'Nombre'
            = form.text_field :name, class: 'form-control',  required: true
          .form-group
            = form.label :description, "Descripción"
            = form.text_area :description, class: 'form-control',  required: true
          %div.flexc-r.space-between
            .form-group
              = form.label :responsible, "Responsable"
              = form.text_field :responsible, class: 'form-control'
            .form-group
              = form.label :start_date, "Fecha de Inicio"
              = form.date_field :start_date, class: 'form-control'
            .form-group
              = form.label :deadline, "Fecha Límite"
              = form.date_field :deadline, class: 'form-control'
          %br/
          %br/
          -# %hr.centered
          -if @tags[1]
            %h4.etiquetas-disponibles.mr-4.mt-2 Etiquetas Disponibles:
            -@tags.each do |tag|
              -if tag[0] != nil && tag[1] != nil
                .form-check.form-check-inline
                  =tag[0]
                  =form.radio_button :tag_id, tag[1], class: 'form-check-input ml-2'
        %section.centered.form
          .form-inline
            .form-group.mt-3
              = form.fields_for :tag, @tag do |tag_fields|
                =tag_fields.label :name, 'Crear nueva etiqueta: ', class: 'mr-4'
                = tag_fields.text_field :name, class: 'form-control '

          -# %hr
          %br
          %br
          %br

          -if !@archivos.empty?
            %h3.mb-4 Archivos Adjuntos
            %div.flex-grid
              -@archivos.each do |a|
                -if a.document.attachment.blob.content_type.split("/")[0] == "image"
                  %div.v.pos-rela
                    =image_tag((a.document), :class => "archivo-wrapper" )
                    %a.optionicon.edit(href= "#{archive_path(a)}" data-method="delete" data-confirm="¿Borrar archivo?") &#xF165
                    -unless a.title.empty?
                      %p.edit-down= a.title

            %div
              -@archivos.each do |a|
                -if a.document.attachment.blob.content_type.split("/")[0] != "image" 
                  %p
                  %div.flexc-r
                    -if !a.title.empty?
                      %li= a.title + "  "
                    -else
                      %li Sin título
                    %a.iconsfont(href= "#{archive_path(a)}" data-method="delete" data-confirm="¿Borrar archivo?") &#xF165

            %hr
          %h3 Adjuntar Archivos
          %div#archives
            = form.fields_for :archives do |archive|
              = link_to_add_association 'Nuevo', form, :archives, class: 'btn btn-warning agregar'
              -# = render 'archive_fields', f: archive
          %hr/
          .actions.d-flex
            = form.submit 'Guardar', class: "btn btn-dark btn-lg archiv right"
          %br/
          %br/

app/views/projects/new.html.haml
%section.dashbrds
  = render :partial => 'shared/sidebar'
  %div.center
    %div.container
      %header.centered.flexc-r
        %div.link
          = link_to '<', :back, class: "icon"
          = link_to 'Volver', :back
          %h3.dashboard-title Nuevo Proyecto
      %hr.centered
      %br/


      = form_with(model: [@account, @project], local: true) do |form|


        %section.centered.form
          - if @project.errors.any?
            #error_explanation
              %h2
                = pluralize(@project.errors.count, "error")
                prohibited this profile from being saved:
              %ul
                - @project.errors.full_messages.each do |message|
                  %li= message

        %section.centered.form
          %h4.tipo-de-proyecto.mr-4.mt-2 Tipo de Proyecto:
          %div.radio
            = form.label :kind, "Estándar", class: 'radiolabel'
            = form.radio_button :kind, :default
            = form.label :kind, "Selectivo", class: 'radiolabel'
            = form.radio_button :kind, :multichoice
          %section.ocss.flexc-r.absolute
            %article.flexc-c.box
              = image_tag 'ico-project.svg', alt: 'icon', height: '100px', class: 'ico-white bright'
              %div
                %h2 Estándar
                %p Carga todo tu trabajo y espera la aprobación completa.
            %article.flexc-c.box.reverse
              = image_tag 'ico-multichoice.svg', alt: 'icon', height: '100px', class: 'ico-white bright'
              %div
                %h2 Selectivo
                %p Carga distintas opciones y espera sólo una aprobación.
          %br/
          %hr/

          %h3 Datos del Proyecto
          .form-group
            = form.label :name, 'Nombre'
            = form.text_field :name, class: 'form-control',  required: true
          .form-group
            = form.label :description, "Descripción"
            = form.text_area :description, class: 'form-control',  required: true
          %div.flexc-r.space-between
            .form-group
              = form.label :responsible, "Responsable"
              = form.text_field :responsible, class: 'form-control',  required: true
            .form-group
              = form.label :start_date, "Fecha de Inicio"
              = form.date_field :start_date, class: 'form-control',  required: true
            .form-group
              = form.label :deadline, "Fecha Límite "
              = form.date_field :deadline, class: 'form-control',  required: true
        -if @tags[1]
          %section.centered.form
            %h4.etiquetas-disponibles.mr-4.mt-2 Etiquetas Disponibles:
            -@tags.each do |tag|
              -if tag[0] != nil && tag[1] != nil
                .form-check.form-check-inline
                  =tag[0]
                  =form.radio_button :tag_id, tag[1], class: 'form-check-input ml-2'

        %section.centered.form
          .form-inline
            .form-group.mt-3
              = form.fields_for :tag, @tag do |tag_fields|
                =tag_fields.label :name, 'Crear nueva etiqueta: ', class: 'mr-4'
                = tag_fields.text_field :name, class: 'form-control '
          %hr
          %h3 Adjuntar Archivos
          %div#archives
            = form.fields_for :archives do |archive|
              = render 'archive_fields', f: archive
              = link_to_add_association 'Agregar Archivo', form, :archives, class: 'btn btn-warning btn-nomarg'



          .actions.d-flex.justify-content-end
            = form.submit 'Guardar', class: "btn btn-dark btn-lg"
      %br/
      %br/

app/views/projects/show.html.haml
%section.dashbrds
  = render :partial => 'shared/sidebar'
  %div.center.uppermargin
    %div.container
      %header.centered.flexc-r
        %div.link
          %div.back
            = link_to '<', :back, class: "icon"
            = link_to 'Volver', :back
          %h3.dashboard-title= "Información de Proyecto"
        -if @project.status == "in_progress"
          %div.small-pad.iconsfont.status.in_progress En Progreso
        -elsif @project.status == "delivered"
          %p.small-pad.iconsfont.status &#xF0A9
        -elsif @project.status == "rejected"
          %p.small-pad.iconsfont.status.rejected &#xF165
        -elsif @project.status == "approved"
          %p.small-pad.iconsfont.status.approved &#xF164

      %hr.centered/
      %br/

      %section.centered.form
        -if !@is_client
          %div.flexc-r.space-between
            %h2.flex100
              Cuenta:
              =link_to "#{@project.account.name}", account_path(@project.account)
            =link_to "Editar Proyecto", edit_project_path(@project), class: 'selectit btn btn-warning'
            =link_to "Eliminar Proyecto", project_path(@project), method: :delete, data: {confirm: "¿Estás seguro?"}, class: 'selectit btn btn-danger'
          %b Nombre del Proyecto:
          %span= @project.name
          %br
          %b Tipo de Proyecto:
          %span= @project.kind
          %br
          %b Descripción:
          %span= @project.description
          %br
        -else
          %h3= @project.name
          %p= @project.description
          %b Responsable:
          %span= @project.responsible
          %br
        %b Fecha de Inicio:
        %span= @project.start_date
        %br
        %b Fecha Límite:
        %span= @project.deadline
        %br
        -if @project.tag
          %b TAG:
          %span= @project.tag.name
          %br
        - unless @is_client
          %b Próximos pasos:
          -if @project.next_steps == ""
            %span= @project.next_steps
            %br
          -else
            %span Sin próximos pasos
            %br
      %br/
      %hr.centered/
      %br/

      %section.centered.form
        -begin
          -index = 0
          -unless @project.archives.empty?
            %h4 Archivo(s)
            %div.flex-grid
              -@project.archives.each do |a|
                -if a.document.attachment.blob.content_type.split("/")[0] == "image"
                  -index += 1
                  %div.v.pos-rela
                    =image_tag((a.document), :class => "archivo-wrapper" )
                    %a{ href: url_for(a.document), download: a.document, target: 'blank', class: 'optionicon edit left' } &#xF0BD
                    -if @is_client && @project.status == "delivered" && @project.kind == "multichoice"
                      %a{ href: update_archive_status_path(project_id: @project.id, id: a.id,  status: "aprobado"), class: "optionicon edit right"} &#xF164
                    -if @is_client && @project.status == "approved" && @project.kind == "multichoice" && a.approved
                      %p.optionicon.edit.right.checked &#xF164
                    -unless a.title.empty?
                      %p.edit-down= a.title
            -unless index == 0
              %br/

            %div
              -@project.archives.each do |a|
                -if a.document.attachment.blob.content_type.split("/")[0] == "video"
                  %div.archiv.v.pos-rela
                    -if a.title != (nil || "")
                      %h5.archivtitle.forvideo= a.title
                    -else
                      %h5.archivtitle.forvideo Sin título
                    = video_tag "#{url_for(a.document)}", controls: true, autobuffer: true, width: "500px"
                    -if @is_client && @project.status == "delivered" && @project.kind == "multichoice"
                      %a{ href: update_archive_status_path(project_id: @project.id, id: a.id,  status: "aprobado"), class: "optionicon edit vidright "} &#xF164
                    -if @is_client && @project.status == "approved" && @project.kind == "multichoice" && a.approved
                      %p.optionicon.edit.vidright.checked &#xF164
                  %hr

            %div.flexc-c.inverted
              -@project.archives.each do |a|
                -if a.document.attachment.blob.content_type.split("/")[0] == "audio"
                  %div.pos-rela
                    -if a.title != (nil || "")
                      %p.archivtitle.foraudio= a.title
                    -else
                      %p.archivtitle.foraudio Sin título
                    = audio_tag "#{url_for(a.document)}", controls: true, preload: "none", autobuffer: true
                    -if @is_client && @project.status == "delivered" && @project.kind == "multichoice"
                      %a{ href: update_archive_status_path(project_id: @project.id, id: a.id,  status: "aprobado"), class: "optionicon foraudio"} &#xF164
                    -if @is_client && @project.status == "approved" && @project.kind == "multichoice" && a.approved
                      %p.optionicon.foraudio.checked &#xF164
                  %hr/
                
            %div.flex-grid
              -@project.archives.each do |a|
                -if a.document.attachment.blob.content_type.split("/")[0] == "application"
                  -index += 1
                  %div.v.pos-rela
                    =image_tag(("ico-file.png"), :class => "archivo-wrapper" )
                    %a{ href: url_for(a.document), target: 'blank', class: 'optionicon edit left' } &#xF0BD
                    -if @is_client && @project.status == "delivered" && @project.kind == "multichoice"
                      %a{ href: update_archive_status_path(project_id: @project.id, id: a.id,  status: "aprobado"), class: "optionicon edit right"} &#xF164
                    -if @is_client && @project.status == "approved" && @project.kind == "multichoice" && a.approved
                      %p.optionicon.edit.right.checked &#xF164
                    -if !a.title.empty?
                      %p.edit-down= a.title
                    -else
                      %p.edit-down= "Archivo " + a.document.attachment.blob.content_type.split("/")[1]
            -unless index == 0
              %br/

        -rescue

      %section.centered.form
        .actions.d-flex.justify-content-center
          -if @project.status == "delivered" && @project.kind == "multichoice" && @is_client
            =link_to 'Rechazar todo', update_project_status_path(id: @project.id, status: "rechazado"), class: 'btn btn-danger'
            %br/
            %hr/
            %br/
          -if @project.status == "delivered" && @project.kind == "default" && @is_client
            =link_to 'Aprobar', update_project_status_path(id: @project.id, status: "aprobado"), class: 'btn btn-success'
            =link_to 'Rechazar', update_project_status_path(id: @project.id, status: "rechazado"), class: 'btn btn-danger ml-5'
            %br/
            %hr/
            %br/
      -# .d-flex.justify-content-center
      %section.centered.form
        .container-comments
          %h3 Comentarios
          %div
            -if @comentarios[1]
              -@comentarios.each do |c|
                %hr/
                -if c.id != nil
                  .message.flex
                    .body
                      .sender
                        -if c.user
                          =c.user.profile.firstname + " dice: "
                        -else
                          = "User:"
                      .date
                        = (c.created_at).strftime("%d/%m/%Y") + " "
                        = (c.created_at).strftime("a las %I:%M%p")
                      .comment
                        =c.content.capitalize
                    .flex.container-botton.icon
                      .botton
                        -if current_user == c.user
                          = link_to comment_path(c.id), method: :delete, data: { confirm: "¿Estás seguro?" } do
                            &#xF165

      %section.centered.form
        = form_with(model: @comments, url: "/projects/#{@project.id}/comments", local: true) do |form|
          - if @comments.errors.any?
            #error_explanation
              %h2
                = pluralize(@comments.errors.count, "error")
                prohibited this profile from being saved:
              %ul
                - @comments.errors.full_messages.each do |message|
                  %li= message
          %div
            = form.text_field :content, class: 'form-control bottommargin', placeholder: 'Escribe tu comentario.'
            =form.submit 'Enviar', class: 'btn btn-warning btn-lg'        
            %br/
            %br/
            %br/