config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, :path_prefix => "my", skip: :registration
  resources :users, only: [:edit, :update, :destroy]
  resources :executives, except: :show
  resources :archives, only: [:destroy]
  resources :accounts, shallow: true do
    resources :projects, except: [:index] do
      resources :comments , only: [:create, :destroy]
    end
  end
  get '/projectstatus/:id/:status', to: 'projects#update_status', as: 'update_project_status'
  get '/archivestatus/:id/:status', to: 'projects#update_approval_archive', as: 'update_archive_status'
end

app/controllers/executives_controller.rb
class ExecutivesController < ApplicationController
  before_action :redirect_if_not_admin
  before_action :set_executive, only: [:show, :destroy, :update]

  def index
    @executives = Profile.executives.map {|profile| profile.user }
  end

  def show
  end

  def new
    @user = User.new
    @profile = @user.build_profile
    @profile[:role_id] = 2
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.new_user(@user,@user.profile).deliver_now
      redirect_to executives_path, notice: 'Executive was successfully created.'
    else
      render :new
    end

  end

  def edit
    @user = User.find(params[:id])
    @profile = @user.profile
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to executives_path, notice: 'Your info was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @executive.accounts.each {|a| a.update({executive_id: nil}) }
    if @executive.destroy
      redirect_to executives_path, notice: "Info was successfully destroyed"
    end
  end

  private

  def set_executive
    @executive = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, profile_attributes: [:firstname, :lastname, :role_id])
  end

  def redirect_if_not_admin
    if current_user.profile.role_id != 1 then redirect_to root_path end
  end
end

app/helpers/executives_helper.rb
module ExecutivesHelper
end

app/views/executives/_form.html.haml
- if @user.errors.any?
  #error_explanation
    %h2
      = pluralize(@user.errors.count, "error")
      prohibited this profile from being saved:
    %ul
      - @user.errors.full_messages.each do |message|
        %li= message
.form-group
  = form.label :email
  = form.email_field :email, class:  "form-control", required: true
// %br/
-if current_page?(new_executive_path)
  .form-group
    = form.label :password
    = form.text_field :password, class:  "form-control", required: true
// %br/
= form.fields_for :profile, @profile do |profile_fields|
  .form-group
    = profile_fields.label :firstname
    = profile_fields.text_field :firstname, class:  "form-control", required: true
  // %br/
  .form-group
    = profile_fields.label :lastname
    = profile_fields.text_field :lastname, class:  "form-control", required: true
    = profile_fields.hidden_field :role_id

app/views/executives/edit.html.haml
%section.dashbrds
  = render :partial => 'shared/sidebar'
  %div.center
    %div.container
      %header.centered.flexc-r
        %div.link
          %div.back
            = link_to '<', :back, class: "icon"
            = link_to 'Volver', :back
          %h3.dashboard-title= "Editar Ejecutivo"
      %hr.centered/
      %br/
      %section.centered.form
        = form_with(model: @user, url: "/executives/#{@user.id}", local: true) do |form|
          =render 'form', form: form 
          %br/
          .actions.d-flex.justify-content-center
            = form.submit 'Guardar Cambios', class: "btn-dark small-pad"

app/views/executives/index.html.haml
%section.dashbrds
  = render :partial => 'shared/sidebar'
  %div.center
    %div.container
      %header.centered.flexc-r
        %div.link
          -# = link_to '<', root_path, class: "icon"
          -# = link_to 'Volver', root_path
          %h3.dashboard-title= "Ejecutivos"
        =link_to 'Crear Ejecutivo', new_executive_path, class: 'btn btn-dark'
      %hr.centered
      %br/
      %section.centered
        - @executives.each do |executive|
          %div.card.text-white.bg-dark.mb-3.small.dontsaturate
            %div.card-head
              %div.card-body.project.title.icon &#xF046
              %div.card-body.project.title #{executive.profile.firstname} #{executive.profile.lastname}
              %p.card-body.date Email: #{executive.email}
            %div
              -unless executive.accounts.empty?
                %p.card-body.small Cuentas asociadas a este ejecutivo:
                - index = 0
                - executive.accounts.each do |a|
                  -if index%2==0
                    %li.card-body.small{:style => "background-color: #29292c;"}= a.name
                    - index += 1
                  -else
                    %li.card-body.small= a.name
                    - index += 1
              -else
                %p.card-body.small Este ejecutivo no tiene ninguna cuenta asociada.
            %div.flexc-r.cardicons
              %a.optionicon(href= "#{edit_executive_path(executive)}") &#xF13A
              %a.optionicon(href= "#{executive_path(executive)}" data-method="delete" data-confirm="¿Quieres borrar este ejecutivo?") &#xF056
        -if @executives.empty?
          %p No hay ejecutivos registrados.

app/views/executives/new.html.haml
%section.dashbrds
  = render :partial => 'shared/sidebar'
  %div.center
    %div.container
      %header.centered.flexc-r
        %div.link
          %div.back
            = link_to '<', :back, class: "icon"
            = link_to 'Volver', :back
          %h3.dashboard-title= "Nuevo Ejecutivo"
      %hr.centered/
      %br/
      %section.centered.form
        = form_with(model: @user, url: "/executives", local: true) do |form|
          =render 'form', form: form 
          %br/
          .actions.d-flex.justify-content-center
            = form.submit 'Crear Ejecutivo', class: "btn-dark small-pad"

app/views/executives/show.html.haml
%h1 Executives#show
%p Find me in app/views/executives/show.html.haml