config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, :path_prefix => "my", skip: :registration
  resources :users, only: [:edit, :update, :destroy]
  resources :executives, except: :show
  resources :archives, only: [:destroy]
  resources :accounts, shallow: true do
    resources :projects, except: [:index] do
      resources :comments , only: [:create, :destroy]
    end
  end
  get '/projectstatus/:id/:status', to: 'projects#update_status', as: 'update_project_status'
  get '/archivestatus/:id/:status', to: 'projects#update_approval_archive', as: 'update_archive_status'
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :client, optional: true,  foreign_key: :client_id, class_name: 'User'
  belongs_to :executive, optional: true, foreign_key: :executive_id, class_name: 'User'

  has_many :projects, dependent: :destroy

  accepts_nested_attributes_for :client

  def projects_by_tag(tag_name)
    projects.joins(:tag).where("tags.name = ?", tag_name)
  end

  def all_my_tags
    projects.map {|p| if p.tag then [p.tag.name, p.tag.id] end }.uniq.compact
  end

  def all_my_tags_uniq_name
    p = projects.map {|p| if p.tag then [p.tag.name, p.tag.id] end }.compact
    p.uniq { |i| i[0] }
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :is_admin?
  before_action :redirect_if_not_admin, except: :show
  before_action :set_account, only: [:show, :edit, :destroy, :update]
  before_action :redirect_if_not_admin_or_associated_executive, only: :show
  before_action :set_executives, only: [:new, :edit, :create]

  def index
    @accounts = Account.all
  end

  def show
    #abort params.inspect
    @account = Account.find(params[:id])
    if @account.projects.any?
      if params[:tag]
        @projects = @account.projects_by_tag(params[:tag])
        # @account.projects.joins(:tag).where(:tags => { :name => params[:format] })
      else
        @projects = @account.projects
      end
      @tags = @account.projects.map { |p| if p.tag then p.tag.name end }.uniq.compact
    end
  end

  def new
    @account = Account.new
    @client = @account.build_client
    @profile = @client.build_profile
    @profile[:role_id] = "3"
  end

  def create
    #abort account_params.inspect
    @account = Account.new(account_params)
    if @account.save
      redirect_to accounts_path, notice: 'Account was successfully created.'
    else
      render :new
    end
  end

  def edit
    @account = Account.find(params[:id])
    @client = @account.client
    @profile = @client.profile
  end

  def update
    @account = Account.find(params[:id])
    if @account.update(account_params)
      redirect_to account_path(@account), notice: 'Your info was successfully updated.'
    else
      render :edit
    end

  end

  def destroy
    @client = @account.client
    if @account.destroy
      @client.destroy
      redirect_to accounts_path, notice: "Info was successfully destroyed"
    end
  end

  private

  def set_account
    @account = Account.find(params[:id])
  end

  def account_params
    params.require(:account).permit(
      :name, :executive_id, client_attributes: [:id, :email, :password, profile_attributes: [:id, :firstname, :lastname, :role_id] ]
    )
  end

  def set_executives
    @executives = Profile.executives.map { |p| ["#{p.firstname} #{p.lastname}" , p.user.id] }
  end

  def is_admin?
    @is_admin = current_user.profile.role_id == 1
  end

  def redirect_if_not_admin
    unless @is_admin then redirect_to root_path end
  end

  def redirect_if_not_admin_or_associated_executive
    @is_executive_in_charge = @account.executive_id == current_user.id
    unless @is_executive_in_charge || @is_admin then redirect_to root_path end
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.haml
.form
  = form_with(model: @account, local: true) do |form|
    - if @account.errors.any?
      #error_explanation
        %h2
          = pluralize(@account.errors.count, "error")
          prohibited this profile from being saved:
        %ul
          - @account.errors.full_messages.each do |message|
            %li= message

    .form-group
      = form.label :name, 'Nombre de la Cuenta'
      = form.text_field :name, class: 'form-control', required: true

    = form.fields_for :client, @client do |client_fields|
      .form-group
        = client_fields.label :email
        = client_fields.email_field :email, class: 'form-control',  required: true
      -if current_page?(new_account_path)
        .form-group
          = client_fields.label :password
          = client_fields.text_field :password, class: 'form-control',  required: true

      = client_fields.fields_for :profile, @profile do |profile_fields|
        .form-group
          = profile_fields.label :firstname, 'Nombre del Contacto'
          = profile_fields.text_field :firstname, class: 'form-control',  required: true
        .form-group
          = profile_fields.label :lastname, 'Apellido del Contacto'
          = profile_fields.text_field :lastname, class: 'form-control',  required: true
          = profile_fields.hidden_field :role_id
    .form-group
      = form.label :executive_id, 'Ejecutivo a Asociar'
      = form.select :executive_id, @executives, {include_blank: true}, {class: 'custom-select'}
    %br/
    .actions.d-flex.justify-content-center
      -if current_page?(controller: "accounts", action: 'new')
        = form.submit 'Crear Cuenta', class: "btn-dark small-pad"
      - unless  @account.id.nil?
        -if current_page?(controller: "accounts", action: 'edit')      
          = form.submit 'Guardar Cambios', class: "btn-dark small-pad"

    %br/
    %br/

app/views/accounts/edit.html.haml
%section.dashbrds
  = render :partial => 'shared/sidebar'
  %div.center
    %div.container
      %header.centered.flexc-r
        %div.link
          %div.back
            = link_to '<', :back, class: "icon"
            = link_to 'Volver', :back
          %h3.dashboard-title= "Editar Cuenta"
      %hr.centered/
      %br/
      %section.centered.form
        =render 'form'

app/views/accounts/index.html.haml
%section.dashbrds
  = render :partial => 'shared/sidebar'
  %div.center
    %div.container
      %header.centered.flexc-r
        %div.link
          -# = link_to '<', root_path, class: "icon"
          -# = link_to 'Volver', root_path
          %h3.dashboard-title= "Cuentas"
        =link_to 'Crear Cuenta', new_account_path, class: 'btn btn-dark'
      %hr.centered
      %br/
      %section.centered
        - @accounts.each do |account|
          %div.forexe
            %a.optionicon(href= "#{account_path(account)}" data-method="delete" data-confirm="¿Quieres borrar esta cuenta? Todos los proyectos, tags y archivos asociados se eliminarán también como consecuencia. Esta acción es irreversible.") &#xF056
          %a.card.text-white.bg-dark.mb-3.small.pos-rela(href="#{account_path(account)}")
            %div.card-head
              %div.card-body.project.title.icon &#xF046
              %div.card-body.project.title= account.name
              %p.card-body.date Email: #{account.client.email}
            %div.flexc-r
              -if account.executive
                %p.card-body.small Ejecutivo a cargo: #{account.executive.profile.firstname} #{account.executive.profile.lastname}
                %p.card-body.small.span Email: #{account.executive.email}
              -else
                %p.card-body.small Sin ejecutivo asociado.
        -if @accounts.empty?
          %p No hay ninguna cuenta registrada.
      %br/

app/views/accounts/new.html.haml
%section.dashbrds
  = render :partial => 'shared/sidebar'
  %div.center
    %div.container
      %header.centered.flexc-r
        %div.link
          %div.back
            = link_to '<', :back, class: "icon"
            = link_to 'Volver', :back
          %h3.dashboard-title= "Nueva Cuenta"
      %hr.centered/
      %br/
      %section.centered.form
        =render 'form'

app/views/accounts/show.html.haml
.v
  %section.dashbrds
    = render :partial => 'shared/sidebar'
    %div.center
      %div.container
        -if current_user.profile.role.kind == "admin"
          %header.centered.flexc-r
            %div.link
              %div.back
                = link_to '<', :back, class: "icon"
                = link_to 'Volver', :back
              %h3.dashboard-title= "Cuenta: " + @account.name
            =link_to 'Editar Cuenta', edit_account_path(@account), class: 'btn btn-dark'
        -else
          %header.centered
            %h3.dashboard-title= "Cuenta: " + @account.name
        %hr.centered
        %br/

        %section.centered.form
          %b Nombre del Contacto/Cliente:
          %span= @account.client.profile.firstname + " " + @account.client.profile.lastname
          %br
          %b Email del Cliente:
          %span= @account.client.email
          %br
          -begin
            -unless !@is_admin
              %b Nombre del Ejecutivo a Cargo:
              %span= @account.executive.profile.firstname + " " + @account.executive.profile.lastname
              %br

              %b Email del Ejecutivo:
              %span= @account.executive.email
              %br
          -rescue
          %br/

        %header.centered.flexc-r
          %div.link
            -# = link_to '<', root_path, class: "icon"
            -# = link_to 'Volver', root_path
            %h3.dashboard-title= "Proyectos"
          =link_to 'Crear Proyecto', new_account_project_path(@account), class: 'btn btn-dark'
        %hr.centered/
        %br/
        %section.centered
          -if @projects
            - @projects.each do |project|
              %a.card.text-white.bg-dark.mb-3.small(href="#{project_path(project)}")
                %div.card-head
                  -if project.kind == "default"
                    %div.card-body.project.title.icon &#xF034
                  -elsif project.kind == "multichoice"
                    %div.card-body.project.title.icon &#xF029

                  %div.card-body.project.title= project.name
                  %p.card-body.date  Fecha límite: #{project.deadline}
                %p.card-body.small= project.description
                %div.tag-corner-position
                  -if project.tag
                    .small-tag
                      = project.tag.name
                  -if project.status == "delivered"
                    .small-tag.delivered-project ENTREGADO
                  -elsif project.status == "approved"
                    .small-tag.approved-project APROVADO
                  -elsif project.status == "rejected"
                    .small-tag.rejected-project RECHAZADO
          -else
            %p Sin proyectos.

        -if @tags
          %hr.centered
          %ul
          %footer.centered.tags
            %h4 Etiquetas:
            %li.small-tag.from-selection=link_to "TODOS", account_path(@account)
            -@tags.each do |tag|
              %li.small-tag.from-selection=link_to "#{tag}", account_path(@account, tag: tag)
          %br/
          %br/